#!/bin/sh
# $Id$
# MFSBSD CUSTOM

# PROVIDE: jcsvpxelinuxcfg
# REQUIRE: FILESYSTEMS

. /etc/rc.subr

name="jcsvpxelinuxcfg"
start_cmd="jcsvpxelinuxcfg_start"
stop_cmd=":"



omitcomments()
{
	/usr/bin/egrep -v '^ *#'
}



dhcpoption()
{
	search=$1
	if [ "dhcp-host" = "${search}" ]; then
		omitcomments | /usr/bin/egrep ${search} | /usr/bin/awk -F, '$5{print $2","$4","$5}'
	elif [ "dhcp-lagg" = "${search}" ]; then
		omitcomments | /usr/bin/egrep ${search} | /usr/bin/awk -F, '$5{split($2,a,"|");for (i in a) {split(a[i],b,"=");print b[2]","$4","$5}}'
	fi
}



jcsvpxelinuxcfg_start()
{



	pxecfgdir=/server/tftp/pxelinux.cfg
	/usr/bin/install -d -m 700	${pxecfgdir}
	for csv in /server/csv/dhcpd/* ; do
		if [ -r ${csv} ]; then
			#echo -n "${csv##*/}... "
			for line in `/bin/cat ${csv} | dhcpoption dhcp-host` ; do
				_mac=$(    echo ${line} | /usr/bin/awk -F, '{print $1}' | /usr/bin/tr ':' '-' | /usr/bin/tr '[A-Z]' '[a-z]' )
				_linkip=$( echo ${line} | /usr/bin/awk -F, '{print $2}' )
				_linkto=$( echo ${line} | /usr/bin/awk -F, '{print $3}' )
				/bin/ln -shf ${_linkto} ${pxecfgdir}/${_linkip}
				/bin/ln -shf ${_linkip} ${pxecfgdir}/01-${_mac}
			done
			unset _mac
			for line in `/bin/cat ${csv} | dhcpoption dhcp-lagg` ; do
				_mac=$(    echo ${line} | /usr/bin/awk -F, '{print $1}' | /usr/bin/tr ':' '-' | /usr/bin/tr '[A-Z]' '[a-z]' )
				_linkip=$( echo ${line} | /usr/bin/awk -F, '{print $2}' )
				_linkto=$( echo ${line} | /usr/bin/awk -F, '{print $3}' )
				/bin/ln -shf ${_linkto} ${pxecfgdir}/${_linkip}
				/bin/ln -shf ${_linkip} ${pxecfgdir}/01-${_mac}
			done
		fi
	done



}

load_rc_config $name
run_rc_command "$1"

