#!/bin/sh
# Copyright (c) 2014 John Ko
# $Id$
# MFSBSD CUSTOM

# PROVIDE: jezjail
# REQUIRE: FILESYSTEMS mdinit NETWORKING pf pflog jroute jautopkg jrcalmost
# KEYWORD: nojail

. /etc/rc.subr

name="jezjail"
start_cmd="jezjail_start"
stop_cmd=":"

jezjail_start()
{

	if [ ! -e /server/bin/jroledhcpdjails ]; then
		/server/bin/jrolebootstrap
	fi
	test -x /server/bin/startezjail && /server/bin/startezjail

}

load_rc_config $name
run_rc_command "$1"

