#!/bin/sh
# $Id$
# MFSBSD CUSTOM

# PROVIDE: jmyrepo
# REQUIRE: FILESYSTEMS NETWORKING
# BEFORE:

. /etc/rc.subr

name="jmyrepo"
start_cmd="jmyrepo_start"
stop_cmd=":"


omitcomments()
{
	/usr/bin/egrep -v '^ *#'
}



jmyrepo_start()
{

	outfile=/usr/local/etc/pkg/repos/myrepo.conf
	/usr/bin/install -d -m 700	${outfile%/*}
	/bin/cat >${outfile} <<EOF
myrepo: {
	URL: http://10.7.7.3/pkgng
	ENABLED: true
	MIRROR_TYPE: none
#	SIGNATURE_TYPE: "pubkey"
#	PUBKEY: "/server/pkg/key.pub"
}
EOF

}

load_rc_config $name
run_rc_command "$1"

