#!/bin/sh
# $Id$
# MFSBSD CUSTOM

# PROVIDE: jping
# REQUIRE: NETWORKING
# KEYWORD: shutdown nojail

#
# Add the following lines to /etc/rc.conf to enable jping:
#
# jping_enable="YES"
#
# Optionally set the following:
# jping_frequency="delay in seconds between jpings"
# jping_ttl="TTL on echo requests"
# jping_target="target to jping"
#

. /etc/rc.subr

name=jping
rcvar=jping_enable

command=/usr/sbin/daemon
procname="/sbin/ping"
pidfile=/var/run/${name}.pid
command_args="-fp $pidfile -u nobody $procname"
start_precmd="start_precmd"

jping_enable=${jping_enable:-"NO"}
jping_frequency=${jping_frequency:-"1"}
jping_ttl=${jping_ttl:-"1"}

load_rc_config $name

start_precmd()
{
	/usr/bin/install -o nobody -g nobody /dev/null $pidfile
	jping_target=${jping_target:-`/sbin/route -n get 0.0.0.0|/usr/bin/sed -n 's/.*ateway. \([0-9]\)/\1/p'`}
	command_args="${command_args} -i${jping_frequency} -m${jping_ttl} -qr ${jping_target}"
}

run_rc_command "$1"
