#!/bin/sh
# Copyright (c) 2014 John Ko
# $Id$

# PROVIDE: jrecover
# REQUIRE: mountcritlocal disks jautomount mdinit tmp var jroute jautopkg jrcdone
# KEYWORD: FreeBSD

. /etc/rc.subr

name="jrecover"
start_cmd="jrecover_start"
stop_cmd=":"

jrecover_start()
{
	recoverdisk=`/bin/kenv -q recoverdisk`
	recoverphase=`/bin/kenv -q recoverphase`
	if [ "xinstall" = "x${recoverphase}" ]; then
		test -x /server/bin/mfsbsd-install && /server/bin/mfsbsd-install
	elif [ "xdata" = "x${recoverphase}" -a "x" != "x${recoverdisk}" ]; then
		test -x /server/bin/zquickdata && /server/bin/zquickdata ${recoverdisk}
		if [ -e /bootdir/boot/loader.conf.local ]; then
			/usr/sbin/sysrc -f /bootdir/boot/loader.conf.local recoverphase=""
			/sbin/reboot
		fi
	fi
}

load_rc_config $name
run_rc_command "$1"
