#!/bin/sh
# Copyright (c) 2014 John Ko
# $Id$
# MFSBSD CUSTOM

# PROVIDE: jroute
# REQUIRE: mountcritlocal disks jautomount mdinit netif jrcalmost
# BEFORE: jautopkg jezjail

. /etc/rc.subr

name="jroute"
start_cmd="jroute_start"
stop_cmd=":"

jroute_start()
{
	test -e /server/csv/ucarp \
	&& local server=$( /bin/cat /server/csv/ucarp | /usr/bin/tr -d '\n' )
	if [ "x" != "x$server" ]; then
		/sbin/route del 10.7.7.0/24 > /dev/null 2> /dev/null
		/sbin/route add 10.7.7.0/24 ${server}
	fi
}

load_rc_config $name
run_rc_command "$1"
