#!/bin/sh
# Copyright (c) 2014 John Ko
# $Id$
# MFSBSD CUSTOM

# PROVIDE: jroute
# REQUIRE: mountcritlocal disks jautomount mdinit netif jrcalmost
# BEFORE: jautopkg jezjail

. /etc/rc.subr

name="jroute"
start_cmd="jroute_start"
stop_cmd=":"

jroute_start()
{
	if [ -e /server/csv/ucarp ]; then
		local server=$( /bin/cat /server/csv/ucarp | /usr/bin/tr -d '\n' )
		if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep -v "no carrier" \
		| /usr/bin/grep . > /dev/null 2> /dev/null ; then
			/sbin/route del 10.7.7.0/24 > /dev/null 2> /dev/null
			/sbin/route add 10.7.7.0/24 ${server}
		fi
	fi
}

load_rc_config $name
run_rc_command "$1"

