#!/bin/sh
# Copyright (c) 2014 John Ko
# $Id$

# PROVIDE: jautopkg
# REQUIRE: mountcritlocal disks jautomount mdinit netif tmp var jroute
# BEFORE: jezjail
# KEYWORD: FreeBSD

. /etc/rc.subr

name="jautopkg"
start_cmd="jautopkg_start"
stop_cmd=":"

jautopkg_start()
{
	local trylocal="NO"
	if [ -x /server/bin/pkgstatic ]; then
		if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep " active" > /dev/null 2> /dev/null ; then
			autopkg=`/bin/kenv -q autopkg`
			TRIMLIST="`echo $autopkg | /usr/bin/tr -d ' '`"
			if [ -n "${TRIMLIST}" ]; then
				echo -n "Installing packages remotely... "
				for i in ${autopkg} ; do
					/server/bin/pkgstatic install -y $i > /dev/null 2> /dev/null || echo "ERROR: pkg install $i"
				done
				echo " done"
			fi
			if ! /server/bin/pkgstatic info | /usr/bin/grep 'rsync' > /dev/null 2> /dev/null; then
				local trylocal="YES"
			fi
		else
			local trylocal="YES"
		fi
		if [ "x$trylocal" = "xYES" ]; then
			PACKAGES=`/bin/ls -1 /packages/*.t?z 2>/dev/null`
			if /bin/test -n "$PACKAGES"; then
				echo -n "Installing from /packages"
				LOOP=1
				while [ $LOOP -eq 1 ]; do
					LOOP=0;
					echo -n '.'
					for i in /packages/*.t?z ; do
						/server/bin/pkgstatic add $i 2>&1 | /usr/bin/grep 'already installed' > /dev/null 2> /dev/null || LOOP=1
					done
				done
				echo " done"
			fi
		fi
	fi
	if /usr/sbin/service -e | /usr/bin/grep usr/local > /dev/null 2> /dev/null; then
		for i in `/usr/sbin/service -e | /usr/bin/grep usr/local` ; do
			$i start
		done
	fi
}

load_rc_config $name
run_rc_command "$1"
