#!/bin/sh
# $Id$

# PROVIDE: jpackages
# BEFORE: LOGIN
# REQUIRE: mdinit tmp var jmyrepo
# KEYWORD: FreeBSD

. /etc/rc.subr

name="jpackages"
start_cmd="jpackages_start"
stop_cmd=":"

jpackages_start()
{
### Logic moved to jautopkg
#	if [ -e /etc/pkg/FreeBSD.conf ]; then
#		/bin/mv /etc/pkg/FreeBSD.conf /etc/pkg.FreeBSD.conf.bkp
#	fi
#	PACKAGES=`/bin/ls -1 /packages/*.t?z 2>/dev/null`
#	if /bin/test -n "$PACKAGES"; then
#		/sbin/mount -t tmpfs tmpfs /var/db/pkg
#		for i in /packages/*.t?z ; do
#			/usr/local/sbin/pkg-static add $i > /dev/null 2> /dev/null || echo "Error jpackages: pkg add $i"
#		done
#	fi
	echo '.'
}

load_rc_config $name
run_rc_command "$1"
